version: '3.8'

services:
  dataprime-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Required - you must set these
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CX_TOKEN=${CX_TOKEN}
      
      # Optional - Coralogix configuration (defaults provided)
      - CX_ENDPOINT=${CX_ENDPOINT:-https://ingress.eu2.coralogix.com:443}
      
      # Service identification for telemetry
      - SERVICE_NAME=dataprime_assistant
      - APPLICATION_NAME=ai-dataprime
      - SUBSYSTEM_NAME=query-generator
      
      # Flask configuration
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-docker-minimal-key-2024}
      - FLASK_ENV=${FLASK_ENV:-production}
      
    volumes:
      # Mount source code for development (optional)
      - ./src:/app/src:ro
      - ./data:/app/data:ro
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      
    restart: unless-stopped
    
    networks:
      - dataprime-network

networks:
  dataprime-network:
    driver: bridge

# To deploy:
# 1. Set your environment variables:
#    export OPENAI_API_KEY="your-key"
#    export CX_TOKEN="your-token"
#
# 2. Build and run:
#    docker-compose up --build
#
# 3. Access the app:
#    http://localhost:8000 