#!/bin/bash
###############################################################################
# AWS Deployment Script
# 
# This script deploys the DataPrime Demo to AWS EC2 using Terraform.
# It handles all the steps: validation, secrets, Terraform apply, SSH key setup.
#
# Prerequisites:
# - Run setup-terraform-backend.sh first
# - Update main.tf with backend configuration
#
# Usage: ./scripts/deploy-aws.sh
###############################################################################

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
TERRAFORM_DIR="$PROJECT_ROOT/infrastructure/terraform"

echo -e "${BLUE}=====================================================================${NC}"
echo -e "${BLUE}DataPrime Demo - AWS Deployment${NC}"
echo -e "${BLUE}=====================================================================${NC}"
echo ""

###############################################################################
# Prerequisites Check
###############################################################################
echo -e "${YELLOW}[1/8] Checking prerequisites...${NC}"

# Check Terraform
if ! command -v terraform &> /dev/null; then
  echo -e "${RED}ERROR: Terraform not installed${NC}"
  exit 1
fi
echo -e "${GREEN}✓ Terraform: $(terraform version | head -n1)${NC}"

# Check AWS CLI
if ! command -v aws &> /dev/null; then
  echo -e "${RED}ERROR: AWS CLI not installed${NC}"
  exit 1
fi
echo -e "${GREEN}✓ AWS CLI: $(aws --version | cut -d' ' -f1)${NC}"

# Check jq
if ! command -v jq &> /dev/null; then
  echo -e "${RED}ERROR: jq not installed${NC}"
  echo "Install: brew install jq (macOS) or apt-get install jq (Linux)"
  exit 1
fi
echo -e "${GREEN}✓ jq installed${NC}"

# Check AWS credentials
if ! aws sts get-caller-identity &> /dev/null; then
  echo -e "${RED}ERROR: AWS credentials not configured${NC}"
  exit 1
fi

AWS_ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
echo -e "${GREEN}✓ AWS Account: $AWS_ACCOUNT${NC}"

###############################################################################
# Navigate to Terraform Directory
###############################################################################
echo ""
echo -e "${YELLOW}[2/8] Navigating to Terraform directory...${NC}"

cd "$TERRAFORM_DIR"
echo -e "${GREEN}✓ Working directory: $(pwd)${NC}"

###############################################################################
# Check for terraform.tfvars
###############################################################################
echo ""
echo -e "${YELLOW}[3/8] Checking for terraform.tfvars...${NC}"

if [ ! -f "terraform.tfvars" ]; then
  echo -e "${YELLOW}terraform.tfvars not found. Creating from example...${NC}"
  
  if [ ! -f "terraform.tfvars.example" ]; then
    echo -e "${RED}ERROR: terraform.tfvars.example not found${NC}"
    exit 1
  fi
  
  # Prompt for required variables
  echo ""
  echo -e "${BLUE}Please provide the following information:${NC}"
  echo ""
  
  read -p "Coralogix Token (CX_TOKEN): " CX_TOKEN
  read -p "OpenAI API Key: " OPENAI_KEY
  read -p "Your IP address for SSH (x.x.x.x/32): " SSH_IP
  
  # Create terraform.tfvars
  cat > terraform.tfvars <<EOF
# Auto-generated by deploy-aws.sh
# Created: $(date)

coralogix_token  = "$CX_TOKEN"
openai_api_key   = "$OPENAI_KEY"
allowed_ssh_cidr = "$SSH_IP"

# Optional overrides (uncomment to customize)
# aws_region = "us-east-1"
# instance_type = "t3.small"
# project_name = "dataprime-demo"
EOF
  
  echo -e "${GREEN}✓ terraform.tfvars created${NC}"
else
  echo -e "${GREEN}✓ terraform.tfvars exists${NC}"
fi

###############################################################################
# Terraform Init
###############################################################################
echo ""
echo -e "${YELLOW}[4/8] Initializing Terraform...${NC}"

terraform init
echo -e "${GREEN}✓ Terraform initialized${NC}"

###############################################################################
# Terraform Plan
###############################################################################
echo ""
echo -e "${YELLOW}[5/8] Creating Terraform plan...${NC}"

terraform plan -out=tfplan
echo -e "${GREEN}✓ Plan created${NC}"

###############################################################################
# Confirm Deployment
###############################################################################
echo ""
echo -e "${BLUE}=====================================================================${NC}"
echo -e "${YELLOW}Ready to deploy to AWS!${NC}"
echo ""
echo -e "${BLUE}Resources to be created:${NC}"
echo -e "  • VPC with public subnet"
echo -e "  • Security group (SSH, HTTP, HTTPS)"
echo -e "  • IAM role for Coralogix integration"
echo -e "  • EC2 t3.small instance"
echo -e "  • 30GB gp3 EBS volume"
echo -e "  • Elastic IP"
echo ""
echo -e "${BLUE}Estimated monthly cost: ~\$18${NC}"
echo -e "${BLUE}=====================================================================${NC}"
echo ""

read -p "Deploy to AWS? (yes/no): " CONFIRM

if [ "$CONFIRM" != "yes" ]; then
  echo -e "${RED}Deployment cancelled${NC}"
  rm tfplan
  exit 0
fi

###############################################################################
# Terraform Apply
###############################################################################
echo ""
echo -e "${YELLOW}[6/8] Deploying infrastructure...${NC}"
echo -e "${BLUE}This will take 2-3 minutes...${NC}"
echo ""

terraform apply tfplan
rm tfplan

echo -e "${GREEN}✓ Infrastructure deployed${NC}"

###############################################################################
# Save SSH Key
###############################################################################
echo ""
echo -e "${YELLOW}[7/8] Saving SSH private key...${NC}"

SSH_KEY_PATH="$HOME/.ssh/dataprime-demo-key.pem"
terraform output -raw ssh_private_key > "$SSH_KEY_PATH"
chmod 600 "$SSH_KEY_PATH"

echo -e "${GREEN}✓ SSH key saved to: $SSH_KEY_PATH${NC}"

###############################################################################
# Get Instance Information
###############################################################################
echo ""
echo -e "${YELLOW}[8/8] Retrieving instance information...${NC}"

INSTANCE_ID=$(terraform output -raw instance_id)
PUBLIC_IP=$(terraform output -raw instance_public_ip)

echo -e "${GREEN}✓ Instance ID: $INSTANCE_ID${NC}"
echo -e "${GREEN}✓ Public IP: $PUBLIC_IP${NC}"

###############################################################################
# Display Access Information
###############################################################################
echo ""
echo -e "${GREEN}=====================================================================${NC}"
echo -e "${GREEN}🎉 Deployment Complete!${NC}"
echo -e "${GREEN}=====================================================================${NC}"
echo ""
echo -e "${BLUE}Instance Information:${NC}"
echo -e "  ID:         $INSTANCE_ID"
echo -e "  Public IP:  $PUBLIC_IP"
echo ""
echo -e "${BLUE}Access Points:${NC}"
echo -e "  Frontend:   ${GREEN}https://$PUBLIC_IP${NC}"
echo -e "  API:        ${GREEN}http://$PUBLIC_IP:8010${NC}"
echo ""
echo -e "${BLUE}SSH Access:${NC}"
echo -e "  ${GREEN}ssh -i ~/.ssh/dataprime-demo-key.pem ubuntu@$PUBLIC_IP${NC}"
echo ""
echo -e "${YELLOW}⏱️  Bootstrap Status:${NC}"
echo -e "The instance is currently installing Docker and starting services."
echo -e "This takes approximately ${YELLOW}5-10 minutes${NC}."
echo ""
echo -e "${BLUE}Monitor bootstrap progress:${NC}"
echo -e "  ${GREEN}ssh -i ~/.ssh/dataprime-demo-key.pem ubuntu@$PUBLIC_IP 'tail -f /var/log/dataprime-bootstrap.log'${NC}"
echo ""
echo -e "${BLUE}Check service health:${NC}"
echo -e "  ${GREEN}./scripts/health-check-aws.sh${NC}"
echo ""
echo -e "${BLUE}Clean up resources:${NC}"
echo -e "  ${GREEN}./scripts/teardown-aws.sh${NC}"
echo ""
echo -e "${GREEN}=====================================================================${NC}"





