#!/bin/bash
# Setup Terraform Backend (S3 + DynamoDB)
# Run this ONCE before deploying infrastructure

set -euo pipefail

echo "========================================="
echo "🔧 Terraform Backend Setup"
echo "========================================="
echo ""

# Check prerequisites
command -v aws >/dev/null 2>&1 || { echo "❌ AWS CLI not found. Install it first."; exit 1; }
command -v terraform >/dev/null 2>&1 || { echo "❌ Terraform not found. Install it first."; exit 1; }

# Variables
PROJECT_NAME="${PROJECT_NAME:-dataprime-demo}"
AWS_REGION="${AWS_REGION:-us-east-1}"
BACKEND_DIR="$(dirname "$0")/../infrastructure/terraform/backend-setup"

# Verify AWS credentials
echo "🔍 Checking AWS credentials..."
if ! aws sts get-caller-identity > /dev/null 2>&1; then
    echo "❌ AWS credentials not configured"
    echo "Run: aws configure"
    exit 1
fi

AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
echo "✅ AWS Account: $AWS_ACCOUNT_ID"
echo "✅ AWS Region: $AWS_REGION"
echo ""

# Confirm before proceeding
read -p "Create Terraform backend resources in $AWS_REGION? (y/N): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 0
fi

# Initialize and apply backend setup
echo ""
echo "📦 Initializing Terraform for backend setup..."
cd "$BACKEND_DIR"

terraform init || { echo "❌ Terraform init failed"; exit 1; }

echo ""
echo "📋 Planning backend resources..."
terraform plan \
    -var="aws_region=$AWS_REGION" \
    -var="project_name=$PROJECT_NAME" \
    -out=tfplan

echo ""
echo "🚀 Creating backend resources..."
terraform apply tfplan

# Get outputs
echo ""
echo "========================================="
echo "✅ Backend Setup Complete!"
echo "========================================="
echo ""

S3_BUCKET=$(terraform output -raw s3_bucket_name)
DYNAMODB_TABLE=$(terraform output -raw dynamodb_table_name)

echo "📝 Backend Configuration:"
echo ""
echo "Add this to infrastructure/terraform/backend.tf:"
echo ""
echo "terraform {"
echo "  backend \"s3\" {"
echo "    bucket         = \"$S3_BUCKET\""
echo "    key            = \"dataprime-assistant/terraform.tfstate\""
echo "    region         = \"$AWS_REGION\""
echo "    dynamodb_table = \"$DYNAMODB_TABLE\""
echo "    encrypt        = true"
echo "  }"
echo "}"
echo ""

# Create backend.tf file
MAIN_TF_DIR="$(dirname "$0")/../infrastructure/terraform"
BACKEND_FILE="$MAIN_TF_DIR/backend.tf"

cat > "$BACKEND_FILE" <<EOF
# Terraform Backend Configuration
# Auto-generated by setup-terraform-backend.sh

terraform {
  backend "s3" {
    bucket         = "$S3_BUCKET"
    key            = "dataprime-assistant/terraform.tfstate"
    region         = "$AWS_REGION"
    dynamodb_table = "$DYNAMODB_TABLE"
    encrypt        = true
  }
}
EOF

echo "✅ Created: $BACKEND_FILE"
echo ""
echo "📋 Next Steps:"
echo "1. cd infrastructure/terraform"
echo "2. terraform init  # Will migrate to S3 backend"
echo "3. terraform plan -var-file=environments/dev.tfvars"
echo "4. terraform apply -var-file=environments/dev.tfvars"
echo ""
echo "Or use the deployment script:"
echo "   ./scripts/deploy-vm.sh"
echo ""

