#!/bin/bash
# Simple status check - just the essentials

ssh -i ~/.ssh/dataprime-demo-key.pem ubuntu@54.235.171.176 << 'EOF'
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ Application Status (WITHOUT Profiling)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Core Services:"
sudo kubectl get pods -n dataprime-demo 2>/dev/null | grep -E "^(product-service|api-gateway|frontend|postgres)" | grep "Running"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Testing Endpoints"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Frontend: https://54.235.171.176:30443"
curl -s -o /dev/null -w "   Status: %{http_code}\n" https://localhost:30443 -k 2>/dev/null || echo "   ❌ Not responding"
echo ""
echo "2. API Gateway: http://54.235.171.176:8010"  
curl -s -o /dev/null -w "   Status: %{http_code}\n" http://localhost:8010/health 2>/dev/null || echo "   ❌ Not responding"
echo ""
echo "3. Scene 9 (Database APM Demo):"
echo "   Endpoint: POST http://54.235.171.176:8010/api/demo/inject-telemetry"
curl -s -X POST http://localhost:8010/api/demo/inject-telemetry -H "Content-Type: application/json" 2>&1 | grep -E "success|error|spans_created" | head -3 || echo "   ❌ Not responding"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  System Health"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Load: $(uptime | awk -F'load average:' '{print $2}')"
echo "Memory: $(free -h | grep Mem | awk '{print $3 "/" $2}')"
echo "Profiling Agent: $(sudo kubectl get pods -n dataprime-demo 2>/dev/null | grep -c ebpf || echo "0") pods (should be 0)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ Demo Ready!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Working Demos:"
echo "  ✓ Scene 9: Database APM (Telemetry Injection)"
echo "    - Run: ./run-scene9-demo.sh"
echo "    - Or click: '🔥 Simulate Database Issues' in frontend"
echo ""
echo "NOT Available (Profiling causes instance crashes):"
echo "  ✗ Scene 9.5: Continuous Profiling"
echo ""
echo "Access URLs:"
echo "  Frontend: https://54.235.171.176:30443"
echo "  API Gateway: http://54.235.171.176:8010"
echo ""
EOF

